alter ROLE KINHDOANH not IDENTIFIED;
select * from sys.batdongsan;
GRANT  SELECT ON BATDONGSAN TO KinhDoanh;
  GRANT  SELECT ON COSOHATANG TO KinhDoanh;
  GRANT  SELECT ON BDSCSHT TO KinhDoanh;
  GRANT  SELECT ON CHUNGCU TO KinhDoanh;
  GRANT  SELECT ON CHUNGCUANH TO KinhDoanh;
  GRANT  SELECT ON CANHO TO KinhDoanh;
  GRANT  SELECT ON NHAPHO TO KinhDoanh;
  GRANT  SELECT ON NHAPHOANH TO KinhDoanh;
  GRANT  SELECT ON KHUDUAN TO KinhDoanh;
  GRANT  SELECT ON DATNEN TO KinhDoanh;
  GRANT  SELECT ON DATNENANH TO KinhDoanh;
  GRANT  SELECT ON BDSDANGBAN TO KINHDOANH;
  GRANT  SELECT ON BDSDANGTHUE TO KinhDoanh;
  --lien quan toi chuong trinh khuyen mai
  GRANT  SELECT ON CHUONGTRINHKM TO KinhDoanh;
  GRANT  SELECT ON BDSKM TO KinhDoanh;
  --lien quan toi viec truy suat thong tin cua nhan vien
  GRANT  SELECT ON NHANVIEN TO KinhDoanh;
  GRANT  SELECT ON NHANVIENBH TO KINHDOANH;
  GRANT  SELECT ON DOANHSOTHANG TO KINHDOANH ;
  -- lien quan toi giao dich thanh cong
  GRANT SELECT,INSERT,UPDATE,DELETE ON GIAODICHTHANHCONG TO KINHDOANH;
GRANT SELECT,INSERT,UPDATE,DELETE ON DOANHSOTHANG TO KINHDOANH;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON NHANVIENBH TO KINHDOANH;
  GRANT  SELECT ON BDSDANGBAN TO KINHDOANH;
  GRANT  SELECT ON BDSDANGTHUE TO KINHDOANH;

