--I.
--1.
CREATE USER DANGTIN IDENTIFIED BY DANGTIN QUOTA 5m ON USERS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
  --2.
CREATE USER NHANSUADMIN IDENTIFIED BY NhanSuAdmin QUOTA 5m ON USERS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
CREATE USER NHANSUCHINHANH1 IDENTIFIED BY NHANSUCHINHANH1 QUOTA 5m ON USERS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
  --3.
CREATE ROLE KINHDOANH Not IDENTIFIED;
CREATE USER KINHDOANHA IDENTIFIED BY KinhDoanhA QUOTA 5m ON USERS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
CREATE USER KINHDOANHB IDENTIFIED BY KINHDOANHB QUOTA 5m ON USERS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
CREATE USER KINHDOANHC IDENTIFIED BY KINHDOANHC QUOTA 5m ON USERS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
  GRANT KINHDOANH TO KinhDoanhA, KINHDOANHB, KINHDOANHC;
  --II.
  --1.
  GRANT CREATE SESSION TO DANGTIN,NHANSUADMIN, NHANSUCHINHANH1, KinhDoanh;
  
  --2.
  --User DangTin ðý?c phép xem, thêm, xóa, s?a thông tin c?a các b?ng liên quan ð?n tin ðãng,
  --khách hàng, b?t ð?ng s?n (các b?ng liên quan ð?n BÐS, CSHT), chýõng tr?nh khuy?n m?i. Ð?ng
  --TH?I CÓ QUY?N XEM THÔNG TIN C?A NHÂN VIÊN BÁN HÀNG (NHÝNG KHÔNG ÐÝ?C TH?Y LÝÕNG VÀ T?NG
  --doanh s?)
  --lien quan toi dangtin, khachhang.
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON TINDANG TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON KHACHHANG TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON TINKHACHHANG TO DANGTIN;
  --lien quan toi batdongsan
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON BATDONGSAN TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON COSOHATANG TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON BDSCSHT TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON CHUNGCU TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON CHUNGCUANH TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON CANHO TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON NHAPHO TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON NHAPHOANH TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON KHUDUAN TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON DATNEN TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON DATNENANH TO DANGTIN;
  --lien quan toi chuong trinh khuyen mai
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON BDSDANGBAN TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON BDSDANGTHUE TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON CHUONGTRINHKM TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON BDSKM TO DANGTIN;
  --lien quan toi viec truy suat thong tin cua khach hang
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON KHACHHANG TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON TINKHACHHANG TO DANGTIN;
  --lien quan toi batdongsan
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON BATDONGSAN TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON COSOHATANG TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON BDSCSHT TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON CHUNGCU TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON CHUNGCUANH TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON CANHO TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON NHAPHO TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON NHAPHOANH TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON KHUDUAN TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON DATNEN TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON DATNENANH TO DANGTIN;
  --lien uan toi chuong trinh khuyen mai
  GRANT  SELECT, INSERT, UPDATE, DELETE ON BDSDANGBAN TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON BDSDANGTHUE TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON CHUONGTRINHKM TO DANGTIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON BDSKM TO DANGTIN;
  --lien quan toi lay thong tin cua nhan vien
  GRANT REFERENCES (MANV, HOTEN, NGAYSINH, CMND, EMAIL, SDT, NAMVAO, CHUCVU, DIACHI, MACN) ON NHANVIEN TO DANGTIN;
  GRANT REFERENCES (MaNV) ON NhanVienBH TO DANGTIN;
  
  GRANT  SELECT,  INSERT,  UPDATE, DELETE ON CHINHANH TO NHANSUADMIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON CHINHANHSDT TO NHANSUADMIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON NHANVIEN TO NHANSUADMIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON DOITAC TO NHANSUADMIN;
  GRANT  SELECT,  INSERT,  UPDATE,DELETE ON NHANVIENBH TO NHANSUADMIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON DOANHSOTHANG TO NHANSUADMIN;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON TINNHANVIENBH TO NHANSUADMIN;
  GRANT  SELECT ON THANHPHO TO NHANSUADMIN;
  GRANT  SELECT ON QUAN TO NHANSUADMIN;
  GRANT  SELECT ON PHUONG TO NHANSUADMIN;
  GRANT  SELECT ON DUONG TO NHANSUADMIN;
  GRANT  SELECT ON SEQ_MANHANVIEN TO NHANSUADMIN;
  --CAC BANG LIEN QUAN TOI NHAN VIEN,  CHI NHANH, DOI TAC
  --1. CHINHANH (MACN, TENCN, SOFAX, DIACHI, MANVTRUONG)
  --2. CHINHANSDT (MACN, SDT)
  --3. NHANVIEN (MANV, HOTEN, NGAYSINH, CMND, EMAIL, SDT, NAMVAO, CHUCVU, LUONG, DIACHI, MACN)
  --4. DOITAC (MADT, TEN, HOTENNLL, SDTNLL, DIACHI, MANV)
  --5. NHANVIENBH (MANV, TONGDOANHSO)
  --6. DOANHSOTHANG (MANV, NAM, THANG, DOANHSO)
  --7. TINNHANVIENBH (MATIN, MANVBH)
  --4. Role KinhDoanh có quy?n xem các b?ng b?t ð?ng s?n (các b?ng liên quan ð?n BÐS, CSHT),
  --CHÝÕNG TR?NH KHUY?N M?I, THÔNG TIN NHÂN VIÊN BÁN HÀNG, DOANH S? THÁNG. Ð?NG TH?I CÓ QUY?N
  --thêm, xóa s?a d? li?u c?a GiaoDichThanhCong
  --cac bang lien quan toi bat dong san
  --lien quan toi batdongsan
  GRANT  SELECT ON BATDONGSAN TO KinhDoanh;
  GRANT  SELECT ON COSOHATANG TO KinhDoanh;
  GRANT  SELECT ON BDSCSHT TO KinhDoanh;
  GRANT  SELECT ON CHUNGCU TO KinhDoanh;
  GRANT  SELECT ON CHUNGCUANH TO KinhDoanh;
  GRANT  SELECT ON CANHO TO KinhDoanh;
  GRANT  SELECT ON NHAPHO TO KinhDoanh;
  GRANT  SELECT ON NHAPHOANH TO KinhDoanh;
  GRANT  SELECT ON KHUDUAN TO KinhDoanh;
  GRANT  SELECT ON DATNEN TO KinhDoanh;
  GRANT  SELECT ON DATNENANH TO KinhDoanh;
  GRANT  SELECT ON BDSDANGBAN TO KINHDOANH;
  GRANT  SELECT ON BDSDANGTHUE TO KinhDoanh;
  --lien quan toi chuong trinh khuyen mai
  GRANT  SELECT ON CHUONGTRINHKM TO KinhDoanh;
  GRANT  SELECT ON BDSKM TO KinhDoanh;
  --lien quan toi viec truy suat thong tin cua nhan vien
  GRANT  SELECT ON NHANVIEN TO KinhDoanh;
  GRANT  SELECT ON NHANVIENBH TO KINHDOANH;
  GRANT  SELECT ON DOANHSOTHANG TO KINHDOANH ;
  -- lien quan toi giao dich thanh cong
  GRANT SELECT,INSERT,UPDATE,DELETE ON GIAODICHTHANHCONG TO KINHDOANH;
GRANT SELECT,INSERT,UPDATE,DELETE ON DOANHSOTHANG TO KINHDOANH;
  GRANT  SELECT,  INSERT,  UPDATE,  DELETE ON NHANVIENBH TO KINHDOANH;
  GRANT  SELECT ON BDSDANGBAN TO KINHDOANH;
  GRANT  SELECT ON BDSDANGTHUE TO KINHDOANH;
--  SELECT USERNAME, PROFILE, ACCOUNT_STATUS FROM DBA_USERS;
-- select * from DBA_ROLE_PRIVS where grantee = 'KINHDOANHB';
--  Select * from role_tab_privs Where   role = 'KINHDOANH';
 
 
 drop user DANGTIN;
 drop user  NHANSUADMIN;
 drop user   NHANSUCHINHANH1;
 drop user  KINHDOANHA;
 drop user KINHDOANHB;
 drop user KINHDOANHC;
 drop role  KINHDOANH ;

